basePath: /
definitions:
  handler.Addressee:
    properties:
      address:
        type: string
      name:
        type: string
    type: object
  handler.Attachments:
    properties:
      contentType:
        type: string
      disposition:
        type: string
      downloadUrl:
        type: string
      filename:
        type: string
      id:
        type: string
      related:
        type: boolean
      size:
        type: integer
      transferEncoding:
        type: string
    type: object
  handler.DetailedMessage:
    properties:
      accountId:
        type: string
      attachments:
        items:
          $ref: '#/definitions/handler.Attachments'
        type: array
      bcc:
        items:
          $ref: '#/definitions/handler.Addressee'
        type: array
      cc:
        items:
          $ref: '#/definitions/handler.Addressee'
        type: array
      createdAt:
        type: string
      downloadUrl:
        type: string
      flagged:
        type: boolean
      from:
        $ref: '#/definitions/handler.Addressee'
      hasAttachments:
        type: boolean
      html:
        items:
          type: string
        type: array
      id:
        type: string
      isDeleted:
        type: boolean
      msgid:
        type: string
      retention:
        type: boolean
      retentionDate:
        type: string
      seen:
        type: boolean
      size:
        type: integer
      subject:
        type: string
      text:
        type: string
      to:
        items:
          $ref: '#/definitions/handler.Addressee'
        type: array
      updatedAt:
        type: string
      verifications: {}
    type: object
  handler.Empty:
    type: object
  handler.GoogleAccount:
    properties:
      accessToken:
        type: string
      email:
        type: string
      name:
        type: string
      picture:
        type: string
      providerAccountId:
        type: string
      providerId:
        type: string
      refreshToken:
        type: string
      userId:
        type: string
    type: object
  handler.Message:
    properties:
      accountId:
        type: string
      createdAt:
        type: string
      downloadUrl:
        type: string
      from:
        $ref: '#/definitions/handler.Addressee'
      hasAttachments:
        type: boolean
      id:
        type: string
      intro:
        type: string
      isDeleted:
        type: boolean
      msgid:
        type: string
      seen:
        type: boolean
      size:
        type: integer
      subject:
        type: string
      to:
        items:
          $ref: '#/definitions/handler.Addressee'
        type: array
      updatedAt:
        type: string
    type: object
  handler.TempAccount:
    properties:
      address:
        type: string
      createdAt:
        type: string
      id:
        type: string
      isDeleted:
        type: boolean
      isDisabled:
        type: boolean
      password:
        type: string
      quota:
        type: integer
      token:
        type: string
      updatedAt:
        type: string
      used:
        type: integer
    type: object
info:
  contact: {}
  description: Mailer Api
  title: MAilere
  version: "1.0"
paths:
  /google/delete:
    get:
      consumes:
      - application/json
      description: delete google session
      operationId: delete google session
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.Empty'
            type: array
      summary: Delete
      tags:
      - Google
  /google/messages:
    get:
      consumes:
      - application/json
      description: Get Messages and content
      operationId: get-google-mess
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      - description: pageToken
        in: query
        name: pageToken
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.Empty'
            type: array
      summary: Messages
      tags:
      - Google
  /google/reg:
    post:
      consumes:
      - application/json
      operationId: get-user-list-manga
      parameters:
      - description: Reg Body
        in: body
        name: body
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.Empty'
            type: array
      summary: RegGoogleAcc
      tags:
      - Google
  /google/session:
    get:
      consumes:
      - application/json
      description: Get Google Session
      operationId: get-google-session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.GoogleAccount'
            type: array
      summary: Get Google Session
      tags:
      - Google
  /temp/delete:
    delete:
      consumes:
      - application/json
      description: delete Temp Session
      operationId: delete-temp-session
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.Empty'
            type: array
      summary: Delete Temp
      tags:
      - Temp
  /temp/message:
    get:
      consumes:
      - application/json
      description: get one Temp messages
      operationId: get-one-temp-message
      parameters:
      - description: messageId
        in: query
        name: messageId
        required: true
        type: string
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.DetailedMessage'
      summary: Temp
      tags:
      - Temp
  /temp/messages:
    get:
      consumes:
      - application/json
      description: get all Temp messages
      operationId: get-temp-messages
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      - description: pageToken
        in: query
        name: pageToken
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.Message'
            type: array
      summary: Temp
      tags:
      - Temp
  /temp/reg:
    get:
      consumes:
      - application/json
      description: get randome tempAcc
      operationId: get-temp-mail
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.TempAccount'
            type: array
      summary: RegTempAcc
      tags:
      - Temp
  /temp/session:
    get:
      consumes:
      - application/json
      description: Get Temp Session
      operationId: get-temp-session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.TempAccount'
            type: array
      summary: Get Temp Session
      tags:
      - Temp
swagger: "2.0"
